version: "3"

services: 
  client:
    build: 
      context: ./client
      dockerfile: ./Dockerfile.client
    environment: 
      - NODE_ENV=development
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app/client
      - node_modules_client:/usr/src/app/client/node_modules
    depends_on: 
      - server
    container_name: pb-client
  server:
    build: 
      context: ./server
      dockerfile: ./Dockerfile.server
    environment:
      - NODE_ENV=development
      - PORT=3001
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app/server
      - node_modules_server:/usr/src/app/server/node_modules
    container_name: pb-server

volumes:
  node_modules_client:
  node_modules_server:

networks: 
  default:
    name: internal
  
    